spring:
  application:
    name: server
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/taskmanagement
    username: postgres
    password: 5432

app:
  jwt:
    secret: rChJvnAPX2d5wsMC/G1AaEtAoAo0GRrL8cA0z5Bl1YaTy+yIrK2DAty5zOHikLQurB3T9z/1nW8FcmQ+mKgDlQ==
    expiration:
      minutes: 10
  cors:
    allowed-origins: http://localhost:3000

logging:
  level:
    org.springframework.security: DEBUG
    # org.hibernate.SQL: DEBUG
