spring:
  application:
    name: server
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5432/taskmanagement
    username: postgres
    password: 5432

app:
  jwt:
    secret: kajslksdjasdhhFdhgfdhgahdcbhjsdfnkgjnj
    expiration:
      minutes: 10
  cors:
    allowed-origins: http://localhost:3000

logging:
  level:
    org.springframework.security: DEBUG
    # org.hibernate.SQL: DEBUG
